# Generated by Django 4.0.3 on 2022-04-05 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_status', models.CharField(default='', max_length=20, null=True)),
                ('lc_start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('lc_end_date', models.DateTimeField(null=True)),
                ('email', models.CharField(blank=True, max_length=200, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=200, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(editable=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_status', models.CharField(default='', max_length=20, null=True)),
                ('lc_start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('lc_end_date', models.DateTimeField(null=True)),
                ('time_zone', models.CharField(default='', max_length=50)),
                ('signup_source', models.CharField(default='', max_length=50)),
                ('language_code', models.CharField(default='', max_length=3)),
                ('nationality_country_code', models.CharField(default='', max_length=2)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='user.member')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
