# Generated by Django 3.1.1 on 2022-04-11 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_member_table_alter_memberprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to='user.member'),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_status', models.CharField(default='', max_length=20, null=True)),
                ('lc_start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('lc_end_date', models.DateTimeField(null=True)),
                ('token', models.TextField(default='')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='user.member')),
            ],
            options={
                'db_table': 'token',
            },
        ),
    ]
