# Generated by Django 3.1.1 on 2022-04-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220411_0622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
