# Generated by Django 3.1.1 on 2022-04-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_status', models.CharField(default='', max_length=20, null=True)),
                ('lc_start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('lc_end_date', models.DateTimeField(null=True)),
                ('token', models.TextField(default='')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='user.member')),
            ],
            options={
                'db_table': 'token',
            },
        ),
    ]
