# Generated by Django 3.1.1 on 2022-04-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='language_code',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='member',
            name='nationality_country_code',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='member',
            name='signup_source',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='time_zone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='MemberProfile',
        ),
    ]
