# Generated by Django 3.1.1 on 2022-04-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220412_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='nationality_country_code',
            new_name='country_code',
        ),
    ]
